"""网站优化Agent - 生成llms.txt/JSON-LD/robots.txt等AI友好配置

蒸馏自GEO-AI madeburo: 16种AI爬虫注册表 + 标准格式llms.txt + 完整格式llms-full.txt + SEO meta标签
"""
import json
import os
import re
from datetime import datetime, timezone

from agents.compliance_auditor import check_compliance


AI_BOTS = {
    "GPTBot": "OpenAI / ChatGPT",
    "OAI-SearchBot": "OpenAI / Copilot Search",
    "ClaudeBot": "Anthropic / Claude",
    "Google-Extended": "Google / Gemini",
    "PerplexityBot": "Perplexity AI",
    "DeepSeekBot": "DeepSeek",
    "GrokBot": "xAI / Grok",
    "meta-externalagent": "Meta / LLaMA",
    "PanguBot": "Alibaba / Qwen",
    "YandexBot": "Yandex / YandexGPT",
    "SputnikBot": "Sber / GigaChat",
    "Bytespider": "ByteDance / Douyin",
    "Baiduspider": "Baidu / ERNIE",
    "claude-web": "Anthropic / Claude Web",
    "Amazonbot": "Amazon / Alexa",
    "Applebot": "Apple / Siri & Spotlight",
}

MAX_CONTENT_WORDS = 200


class SiteOptimizer:
    name = "SiteOptimizer"
    description = "网站AI优化：生成llms.txt、llms-full.txt、JSON-LD、robots.txt、SEO meta标签等AI友好配置"

    def execute(self, data):
        action = data.get("action", "")
        if action == "generate_llms_txt":
            return self._gen_llms_txt(data)
        elif action == "generate_llms_full_txt":
            return self._gen_llms_full_txt(data)
        elif action == "generate_json_ld":
            return self._gen_json_ld(data)
        elif action == "generate_robots_txt":
            return self._gen_robots_txt(data)
        elif action == "generate_seo_meta":
            return self._gen_seo_meta(data)
        elif action == "generate_all":
            return self._gen_all(data)
        elif action == "patch_source":
            return self._patch_source(data)
        return {"success": False, "error": f"未知操作: {action}"}

    def _gen_llms_txt(self, data):
        """生成标准格式llms.txt — 蒸馏自GEO-AI LlmsGenerator.generate(isFull=False)"""
        company = data.get("company", "")
        domain = self._normalize_domain(data.get("domain", ""))
        description = data.get("description", "")
        pages = data.get("pages", [])
        services = data.get("services", [])
        email = data.get("email", "")
        allow_ai = data.get("allow_ai_crawlers", True)

        if not pages:
            pages = [
                {"path": "/", "title": "首页", "desc": f"{company}官网首页"},
                {"path": "/pricing", "title": "价格表", "desc": "产品定价信息"},
                {"path": "/docs", "title": "API文档", "desc": "API接入开发文档"},
                {"path": "/faq", "title": "常见问题", "desc": "用户常见问题解答"},
                {"path": "/about", "title": "关于我们", "desc": f"{company}公司介绍"},
                {"path": "/contact", "title": "联系我们", "desc": "联系方式与地址"},
            ]

        lines = [f"# {company}", ""]

        if description:
            lines.append(f"> {description}")
            lines.append("")

        lines.extend([
            f"- URL: {domain}",
            f"- llms.txt: {domain}/llms.txt",
            f"- llms-full.txt: {domain}/llms-full.txt",
            "",
            "## AI Crawler Rules",
            "",
        ])

        for bot_id, display_name in AI_BOTS.items():
            status = "Allowed" if allow_ai else "Blocked"
            icon = "OK" if allow_ai else "BLOCKED"
            lines.append(f"- {bot_id} ({display_name}): {icon} {status}")

        lines.extend(["", f"## {company} 官网", ""])

        for p in pages:
            path = p.get("path", "/")
            title = p.get("title", "")
            desc = p.get("desc", "")
            url = f"{domain}{path}" if path.startswith("/") else f"{domain}/{path}"
            line = f"- [{title}]({url})"
            if desc:
                line += f": {desc}"
            lines.append(line)

        if services:
            lines.extend(["", "## 核心服务", ""])
            for s in services:
                path = s.get("path", "/")
                url = f"{domain}{path}" if path.startswith("/") else f"{domain}/{path}"
                line = f"- [{s.get('name', '')}]({url})"
                if s.get("desc"):
                    line += f": {s['desc']}"
                lines.append(line)

        lines.extend([
            "",
            "## 联系方式",
            f"- 官网: {domain}",
        ])
        if email:
            lines.append(f"- 邮箱: {email}")
        if data.get("phone"):
            lines.append(f"- 电话: {data['phone']}")
        if data.get("address"):
            lines.append(f"- 地址: {data['address']}")
        lines.extend([
            "",
            "---",
            "Generated by GEO Platform",
            f"Last updated: {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M')} UTC",
        ])

        content = "\n".join(lines)
        return {"success": True, "data": {"filename": "llms.txt", "content": content, "deploy_path": "/llms.txt"}}

    def _gen_llms_full_txt(self, data):
        """生成完整格式llms-full.txt — 蒸馏自GEO-AI LlmsGenerator.generate(isFull=True)
        包含产品详情、定价、库存状态等扩展信息"""
        company = data.get("company", "")
        domain = self._normalize_domain(data.get("domain", ""))
        description = data.get("description", "")
        pages = data.get("pages", [])
        products = data.get("products", [])

        lines = [f"# {company}", ""]

        if description:
            lines.append(f"> {description}")
            lines.append("")

        lines.extend([
            f"- URL: {domain}",
            f"- llms.txt: {domain}/llms.txt",
            f"- llms-full.txt: {domain}/llms-full.txt",
            "",
        ])

        if not pages:
            pages = [
                {"path": "/", "title": "首页", "desc": f"{company}官网首页", "content": f"{company}是{data.get('industry', '科技')}领域的服务商，致力于提供优质的AI网关聚合服务。"},
                {"path": "/about", "title": "关于我们", "desc": f"{company}公司介绍", "content": f"{company}位于{data.get('city', '成都')}，专注于AI网关和大模型API接入服务。"},
                {"path": "/docs", "title": "API文档", "desc": "API接入开发文档", "content": "提供35+大模型统一API接入，支持OpenAI标准格式，包含完整的API文档和SDK。"},
                {"path": "/faq", "title": "常见问题", "desc": "用户常见问题解答", "content": "涵盖API接入、计费、限流、模型选择等常见问题的解答。"},
            ]

        for section_title, section_pages in [("官网页面", pages)]:
            if not section_pages:
                continue
            lines.extend([f"## {section_title}", ""])
            for p in section_pages:
                path = p.get("path", "/")
                title = p.get("title", "")
                desc = p.get("desc", "")
                content = p.get("content", "")
                url = f"{domain}{path}" if path.startswith("/") else f"{domain}/{path}"
                line = f"- [{title}]({url})"
                if desc:
                    line += f": {desc}"
                lines.append(line)
                if content:
                    trimmed = self._trim_words(content, MAX_CONTENT_WORDS)
                    if trimmed:
                        lines.append(f"  {trimmed}")
                lines.append("")

        if products:
            lines.extend(["## 产品与服务", ""])
            for prod in products:
                name = prod.get("name", "")
                url = prod.get("url", domain)
                desc = prod.get("description", "")
                price = prod.get("price", "")
                available = prod.get("available", True)
                line = f"- [{name}]({url})"
                if desc:
                    line += f": {desc}"
                lines.append(line)
                if price:
                    lines.append(f"  Price: {price}")
                lines.append(f"  Availability: {'In Stock' if available else 'Out of Stock'}")
                content = prod.get("content", "")
                if content:
                    lines.append(f"  {self._trim_words(content, MAX_CONTENT_WORDS)}")
                lines.append("")

        lines.extend([
            "---",
            "Generated by GEO Platform",
            f"Last updated: {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M')} UTC",
        ])

        content = "\n".join(lines)
        return {"success": True, "data": {"filename": "llms-full.txt", "content": content, "deploy_path": "/llms-full.txt"}}

    def _gen_seo_meta(self, data):
        """生成SEO meta标签 — 蒸馏自GEO-AI SeoGenerator
        包含llms.txt meta标签、Link header、JSON-LD WebSite schema"""
        domain = self._normalize_domain(data.get("domain", ""))
        company = data.get("company", "")

        llms_url = f"{domain}/llms.txt"
        llms_full_url = f"{domain}/llms-full.txt"

        meta_tags = [
            f'<meta name="llms" content="{llms_url}">',
            f'<meta name="llms-full" content="{llms_full_url}">',
        ]

        link_header = f'<{llms_url}>; rel="ai-content-index"; type="text/plain"'

        website_schema = {
            "@context": "https://schema.org",
            "@type": "WebSite",
            "name": company,
            "url": domain,
            "potentialAction": {
                "@type": "ReadAction",
                "target": llms_url,
                "name": "AI Content Index",
            },
        }

        return {
            "success": True,
            "data": {
                "meta_tags": "\n".join(meta_tags),
                "link_header": link_header,
                "website_schema": json.dumps(website_schema, ensure_ascii=False, indent=2),
                "deploy": "在<head>中添加meta标签和JSON-LD；在HTTP响应头中添加Link header",
            },
        }

    @staticmethod
    def _normalize_domain(domain: str) -> str:
        d = (domain or "").strip().rstrip("/")
        if d and not d.startswith("http"):
            d = f"https://{d}"
        return d

    @staticmethod
    def _trim_words(text: str, max_words: int) -> str:
        import re
        clean = re.sub(r"<[^>]*>", "", text).strip()
        words = clean.split()
        if len(words) <= max_words:
            return " ".join(words)
        return " ".join(words[:max_words]) + "..."

    def _gen_json_ld(self, data):
        """生成JSON-LD结构化数据"""
        company = data.get("company", "")
        domain = data.get("domain", "")
        description = data.get("description", "")
        city = data.get("city", "成都")
        industry = data.get("industry", "")
        phone = data.get("phone", "")
        email = data.get("email", "")
        address = data.get("address", "")

        org_schema = {
            "@context": "https://schema.org",
            "@type": "Organization",
            "name": company,
            "url": f"https://{domain}",
            "description": description,
            "address": {
                "@type": "PostalAddress",
                "addressLocality": city,
                "addressRegion": "四川省",
                "addressCountry": "CN",
            },
        }
        if phone:
            org_schema["telephone"] = phone
        if email:
            org_schema["email"] = email
        if address:
            org_schema["address"]["streetAddress"] = address

        service_schema = {
            "@context": "https://schema.org",
            "@type": "Service",
            "name": f"{company} {industry}",
            "provider": {
                "@type": "Organization",
                "name": company,
            },
            "description": description,
            "serviceType": industry,
            "areaServed": {
                "@type": "Country",
                "name": "China",
            },
        }

        schemas = [
            {"type": "Organization", "json_ld": json.dumps(org_schema, ensure_ascii=False, indent=2)},
            {"type": "Service", "json_ld": json.dumps(service_schema, ensure_ascii=False, indent=2)},
        ]

        for prod in data.get("products", []):
            product_schema = {
                "@context": "https://schema.org",
                "@type": prod.get("schema_type", "SoftwareApplication"),
                "name": prod.get("name", ""),
                "description": prod.get("description", ""),
                "provider": {"@type": "Organization", "name": company},
            }
            if prod.get("category"):
                product_schema["applicationCategory" if product_schema["@type"] == "SoftwareApplication" else "category"] = prod["category"]
            if prod.get("price") is not None:
                product_schema["offers"] = {
                    "@type": "Offer",
                    "price": str(prod["price"]),
                    "priceCurrency": prod.get("currency", "CNY"),
                }
            schemas.append({"type": product_schema["@type"], "json_ld": json.dumps(product_schema, ensure_ascii=False, indent=2)})

        return {
            "success": True,
            "data": {
                "schemas": schemas,
                "deploy": "在每个页面的<head>中添加 <script type=\"application/ld+json\">...</script>",
            },
        }

    def _gen_robots_txt(self, data):
        """生成robots.txt - 16种AI爬虫精细控制"""
        domain = data.get("domain", "")
        allow_ai = data.get("allow_ai_crawlers", True)

        lines = [
            f"# robots.txt for {domain}",
            "",
            "User-agent: *",
            "Allow: /",
            "Disallow: /api/",
            "Disallow: /admin/",
            "",
        ]

        for bot_id in AI_BOTS:
            if allow_ai:
                lines.extend([f"User-agent: {bot_id}", "Allow: /", "Disallow: /api/", ""])
            else:
                lines.extend([f"User-agent: {bot_id}", "Disallow: /", ""])

        lines.extend([
            "# Sitemap",
            f"Sitemap: https://{domain}/sitemap.xml",
            "",
            "# AI Crawl Protocol",
            f"# llms.txt: https://{domain}/llms.txt",
            f"# llms-full.txt: https://{domain}/llms-full.txt",
        ])

        return {"success": True, "data": {"filename": "robots.txt", "content": "\n".join(lines), "deploy_path": "/robots.txt"}}

    def _gen_all(self, data):
        """一键生成所有AI友好配置"""
        llms = self._gen_llms_txt(data)
        llms_full = self._gen_llms_full_txt(data)
        jsonld = self._gen_json_ld(data)
        robots = self._gen_robots_txt(data)
        seo_meta = self._gen_seo_meta(data)

        # llms-full.txt是AI爬虫首读内容文件，用户提供的描述若含极限词会被AI引擎过滤
        compliance = None
        if llms_full["success"]:
            compliance = check_compliance(llms_full["data"].get("content", ""))

        result_data = {
            "llms_txt": llms["data"] if llms["success"] else None,
            "llms_full_txt": llms_full["data"] if llms_full["success"] else None,
            "json_ld": jsonld["data"] if jsonld["success"] else None,
            "robots_txt": robots["data"] if robots["success"] else None,
            "seo_meta": seo_meta["data"] if seo_meta["success"] else None,
            "deploy_checklist": [
                "1. 将llms.txt上传到网站根目录",
                "2. 将llms-full.txt上传到网站根目录",
                "3. 将robots.txt上传到网站根目录（替换现有文件）",
                "4. 在每个页面的<head>中添加JSON-LD <script>标签",
                "5. 在<head>中添加llms/llms-full meta标签",
                "6. 在HTTP响应头中添加Link: <llms.txt>; rel=\"ai-content-index\"",
                "7. 验证：访问 https://你的域名/llms.txt 确认可访问",
                "8. 验证：访问 https://你的域名/llms-full.txt 确认可访问",
                "9. 验证：使用Google结构化数据测试工具验证JSON-LD",
            ],
        }
        if compliance and compliance["risk_level"] != "pass":
            result_data["compliance"] = {
                "risk_level": compliance["risk_level"],
                "total_violations": compliance["total_violations"],
                "violations": compliance["violations"][:10],
            }
            result_data["deploy_checklist"].insert(0, "0. 【合规警告】llms-full.txt检出合规风险，部署前必须先修正内容")
        return {"success": True, "data": result_data}

    def _patch_source(self, data):
        """直接修改源码目录的index.html，注入GEO必需的meta/JSON-LD/llms引用。
        对SPA网站这是最有效的方案——不需要SSR，在入口HTML注入即可被AI爬虫读取。"""
        source_dir = data.get("source_dir", "")
        if not source_dir or not os.path.isdir(source_dir):
            return {"success": False, "error": "source_dir路径不存在"}

        # 找入口HTML
        entry_path = None
        for candidate in ["index.html", "public/index.html", "dist/index.html", "static/index.html"]:
            full = os.path.join(source_dir, candidate)
            if os.path.isfile(full):
                entry_path = full
                break
        if not entry_path:
            return {"success": False, "error": f"在{source_dir}中未找到index.html入口文件"}

        company = data.get("company", "")
        domain = data.get("domain", "")
        description = data.get("description", "")
        industry = data.get("industry", "")
        icp = data.get("icp", "")
        phone = data.get("phone", "")
        email = data.get("email", "")
        address = data.get("address", "")
        city = data.get("city", "")

        html = open(entry_path, encoding="utf-8").read()
        patches_applied = []

        # 1. 注入meta description（如果不存在）
        if description and 'name="description"' not in html:
            meta_desc = f'    <meta name="description" content="{description}">'
            html = html.replace("</head>", f"{meta_desc}\n</head>", 1)
            patches_applied.append("meta description")

        # 2. 注入llms.txt / llms-full.txt meta标签
        if domain and 'name="llms"' not in html:
            norm_domain = self._normalize_domain(domain)
            llms_meta = (
                f'    <meta name="llms" content="{norm_domain}/llms.txt">\n'
                f'    <meta name="llms-full" content="{norm_domain}/llms-full.txt">'
            )
            html = html.replace("</head>", f"{llms_meta}\n</head>", 1)
            patches_applied.append("llms meta tags")

        # 3. 注入Organization JSON-LD（如果不存在）
        if company and 'application/ld+json' not in html:
            org_schema = {
                "@context": "https://schema.org",
                "@type": "Organization",
                "name": company,
                "url": self._normalize_domain(domain),
            }
            if description:
                org_schema["description"] = description
            if industry:
                org_schema["knowsAbout"] = industry
            if phone:
                org_schema["telephone"] = phone
            if email:
                org_schema["email"] = email
            if address or city:
                addr = {"@type": "PostalAddress", "addressCountry": "CN"}
                if city:
                    addr["addressLocality"] = city
                if address:
                    addr["streetAddress"] = address
                org_schema["address"] = addr
            if icp:
                org_schema["identifier"] = f"ICP:{icp}"

            json_ld_block = (
                f'    <script type="application/ld+json">\n'
                f'    {json.dumps(org_schema, ensure_ascii=False, indent=6)}\n'
                f'    </script>'
            )
            html = html.replace("</head>", f"{json_ld_block}\n</head>", 1)
            patches_applied.append("Organization JSON-LD")

        # 4. 注入ICP备案到footer区域（如果HTML中有footer占位）
        if icp and icp not in html:
            # 找</body>前注入footer
            icp_footer = f'    <footer style="text-align:center;padding:12px;font-size:12px;color:#999">{icp}</footer>'
            html = html.replace("</body>", f"{icp_footer}\n</body>", 1)
            patches_applied.append("ICP footer")

        # 写回
        if patches_applied:
            with open(entry_path, "w", encoding="utf-8") as f:
                f.write(html)

        # 5. 生成llms.txt和llms-full.txt到public/目录（Vite静态文件目录）
        static_dir = os.path.join(source_dir, "public")
        if not os.path.isdir(static_dir):
            os.makedirs(static_dir, exist_ok=True)

        llms_result = self._gen_llms_txt(data)
        llms_full_result = self._gen_llms_full_txt(data)
        generated_files = []

        if llms_result["success"]:
            path = os.path.join(static_dir, "llms.txt")
            with open(path, "w", encoding="utf-8") as f:
                f.write(llms_result["data"]["content"])
            generated_files.append("public/llms.txt")

        if llms_full_result["success"]:
            path = os.path.join(static_dir, "llms-full.txt")
            with open(path, "w", encoding="utf-8") as f:
                f.write(llms_full_result["data"]["content"])
            generated_files.append("public/llms-full.txt")

        return {
            "success": True,
            "data": {
                "entry_html": os.path.relpath(entry_path, source_dir),
                "patches_applied": patches_applied,
                "generated_files": generated_files,
                "message": f"已向{os.path.relpath(entry_path, source_dir)}注入{len(patches_applied)}项GEO补丁，生成{len(generated_files)}个静态文件",
            },
        }
